#!/bin/sh
#######################################
#  ____ ____  ______        ____  __  #
# | __ ) ___||  _ \ \      / /  \/  | #
# |  _ \___ \| |_) \ \ /\ / /| |\/| | #
# | |_) |__) |  __/ \ V  V / | |  | | #
# |____/____/|_|     \_/\_/  |_|  |_| #
#######################################

# AutoStart

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

killall bar.sh
$HOME/.config/bspwm/bar.sh &

killall xfce4-clipman
xfce4-clipman &

killall idle.sh
$HOME/.config/i3/scripts/idle.sh &

killall udiskie
udiskie &

killall xcompmgr
xcompmgr &

# killall picom
# picom --config /etc/xdg/picom.conf &

# Workspaces
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

bspc monitor DP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 10

wmname LG3D

# BSPWM Config
bspc config border_width        2
bspc config window_gap          5
bspc config top_padding         5
bspc config bottm_padding       0
bspc config left_padding        0
bspc config right_padding       0

bspc config single_monocle                false
bspc config click_to_focus                true

bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color        "#4c566a"
bspc config active_border_color        "#1e1e1e"
bspc config focused_border_color       "#5e81ac"
bspc config presel_feedback_color      "#5e81ac"
bspc config urgent_border_color        "#dd2727"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a qutebrowser desktop='^1'
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a firefox desktop='^3'
# bspc rule -a thunar desktop='^4'
bspc rule -a mpv desktop='^5'
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Monitor
# bspc config remove_disabled_monitors      true
# bspc config merge_overlapping_monitors    true
