#!/bin/sh

#oooooo   oooooo     oooo           oooo                              .o8  
# `888.    `888.     .8'            `888                             "888  
#  `888.   .8888.   .8'    .ooooo.   888   .oooo.   ooo. .oo.    .oooo888  
#   `888  .8'`888. .8'    d88' `88b  888  `P  )88b  `888P"Y88b  d88' `888  
#    `888.8'  `888.8'     888   888  888   .oP"888   888   888  888   888  
#     `888'    `888'      888   888  888  d8(  888   888   888  888   888  
#      `8'      `8'       `Y8bod8P' o888o `Y888""8o o888o o888o `Y8bod88P" 

#oooooooooo.   .oooooo..o ooooooooo.   
#`888'   `Y8b d8P'    `Y8 `888   `Y88. 
# 888     888 Y88bo.       888   .d88' 
# 888oooo888'  `"Y8888o.   888ooo88P'  
# 888    `88b      `"Y88b  888         
# 888    .88P oo     .d8P  888         
#o888bood8P'  8""88888P'  o888o        
#

# AutoStart

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

killall bar.sh
$HOME/.config/bspwm/bar.sh &

killall xfce4-clipman
xfce4-clipman &

killall idle.sh
$HOME/.config/i3/scripts/idle.sh &

killall udiskie
udiskie &

killall xcompmgr
xcompmgr &

# killall picom
# picom --config /etc/xdg/picom.conf &

# Workspaces
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

bspc monitor DP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 10

wmname LG3D

# BSPWM Config
bspc config border_width        2
bspc config window_gap          5
bspc config top_padding         5
bspc config bottm_padding       0
bspc config left_padding        0
bspc config right_padding       0

bspc config single_monocle                false
bspc config click_to_focus                true

bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color        "#4c566a"
bspc config active_border_color        "#1e1e1e"
bspc config focused_border_color       "#5e81ac"
bspc config presel_feedback_color      "#5e81ac"
bspc config urgent_border_color        "#dd2727"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a qutebrowser desktop='^1'
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a firefox desktop='^3'
# bspc rule -a thunar desktop='^4'
bspc rule -a mpv desktop='^5'
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Monitor
# bspc config remove_disabled_monitors      true
# bspc config merge_overlapping_monitors    true
